const coffeeCategories = {
  process: [
    "Culturing",
    "Washing",
    "Natural",
    "Nitro",
    "Descafeinado con extracto de caña de azúcar",
    "Various",
    "Honey",
  ],
  variety: [
    "Caturra",
    "Yellow Bourbon",
    "Rosé Bourbon",
    "Bourbon (Red, Yellow and Pink)",
    "Red Bourbon",
    "Catiope",
    "Gesha",
    "Borbón rosado (Natural)",
    "Sudan Rumé",
    "Blend (Gesha, Red Bourbon, Tekisic)",
    "Blend Castillo",
    "Castle",
  ],
  flavor_tags: [
    "fruity",
    "sweet",
    "aromatic",
    "citrus",
    "clean",
    "floral",
    "balanced",
    "spiced",
    "wild",
    "natural",
    "creamy",
    "fermented",
    "complex",
    "mild",
    "spicy",
    "intense",
    "earthy",
    "bright",
    "varied",
    "exploratory",
    "caramel",
    "rich",
    "smooth",
  ],
  body: ["full", "light", "medium", "varied"],
  acidity: ["medium", "high", "low", "varied"],
  mood_tags: [
    "experimental",
    "vibrant",
    "bold",
    "bright",
    "refreshing",
    "classic",
    "delicate",
    "smooth",
    "elegant",
    "cheerful",
    "vivid",
    "warm",
    "earthy",
    "complex",
    "innovative",
    "refined",
    "aromatic",
    "gentle",
    "balanced",
    "relaxing",
    "pleasant",
    "reliable",
    "rich",
    "lively",
    "harmonious",
    "adventurous",
    "curious",
    "fun",
    "festive",
    "gift",
    "special",
    "calm",
  ],
  expected_flavor: [
    "funky",
    "aromatic",
    "clean",
    "bright",
    "complex",
    "rich",
    "juicy",
    "fermented",
    "vivid",
    "smooth",
    "balanced",
    "soft",
    "chocolatey",
    "fruity",
    "layered",
    "mixed",
    "exploratory",
    "diverse",
    "honeyed",
    "sweet",
    "nutty",
    "floral",
    "fruit-forward",
  ],
  notes: [
    "blackberry",
    "sugarcane",
    "grape",
    "fermented",
    "full-bodied",
    "complex",
    "honey",
    "mandarin",
    "vibrant",
    "light-bodied",
    "fresh",
    "peach",
    "floral",
    "caramel",
    "round",
    "balanced",
    "cherry",
    "raspberry",
    "vanilla",
    "juicy",
    "refined",
    "apple",
    "refreshing",
    "silky",
    "oak",
    "rum",
    "unique",
    "white chocolate",
    "plums",
    "blackberries",
    "bright",
    "catiope",
    "natural",
    "fruity",
    "distinctive",
    "caturra",
    "nitro",
    "gesha",
    "culturing",
    "medium-bodied",
    "borbón rosado",
    "decaf",
    "canela",
    "lima",
    "chocolate",
    "smooth",
    "washed",
    "sudan rumé",
    "tangerine",
    "toffee",
    "sweet",
    "red bourbon",
    "tekisic",
    "mix box",
    "brew bags",
    "varied flavors",
    "exploratory",
    "fun",
    "mixed box",
    "drip bags",
    "10 varieties",
    "convenient",
    "combo pack",
    "varied",
    "gift",
    "special",
    "mucilage",
    "blend",
    "rich",
    "castle",
    "classic",
    "cultured",
    "aromatic",
  ],
};

export default coffeeCategories;
